language: python
python:
 - "2.7"
before_install:
 - sudo apt-get update
 - sudo apt-get install openjdk-7-jdk icedtea-7-plugin
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
install:
 - pip install -r requirements.txt
services:
 - rabbitmq
before_script:
 - sudo rabbitmqctl add_vhost adsfulltext
 - sudo rabbitmqctl add_vhost external_vhost
 - sudo rabbitmqctl set_permissions -p adsfulltext guest ".*" ".*" ".*"
 - sudo rabbitmqctl set_permissions -p external_vhost guest ".*" ".*" ".*"
script:
 - coverage run -p --source=. tests/test_unit/test.py
 - tests/integration_test.sh
 - mvn test
after_success:
 - coverage combine
 - coveralls
