language: python
python:
 - "2.7"
before_install:
 - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections && sudo add-apt-repository ppa:webupd8team/java -y
 - sudo apt-get update
 - sudo apt-get install openjdk-7-jdk icedtea-7-plugin
 - export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/
install:
 - pip install -r requirements.txt
services:
 - rabbitmq
before_script:
 - export PYTHONPATH=$PYTHONPATH:$(pwd)
 - rabbitmqctl add_vhost adsfulltext
 - rabbitmqctl set_permissions -p adsfulltext guest ".*" ".*" ".*"
script:
 - nosetests -w tests/test_unit/ test.py
 - tests/integration_test.sh
 - mvn test
