RABBITMQ_URI: amqp://guest:guest@localhost:5672/adsfulltext?socket_timeout=10&backpressure_detection=t
ERROR_HANDLER:
  exchange: FulltextExtractionExchange
  routing_key: ErrorHandlerRoute
EXCHANGES:
  - exchange: FulltextExtractionExchange
    exchange_type: direct
    durable: true
    passive: false
    autoDelete: false
QUEUES:
  -
    queue: CheckIfExtractQueue
    durable: true
  -
    queue: PDFFileExtractorQueue
    durable: true
  -
    queue: StandardFileExtractorQueue
    durable: true
  -
    queue: WriteMetaFileQueue
    durable: true
  -
    queue: ErrorHandlerQueue
    durable: true
  -
    queue: ProxyPublishQueue
    durable: true